runopsio/agent

.github/workflows/build-publish.yml
project.clj
resources/agent.proto
src/agent/agent.clj
src/agent/core.clj
src/agent/grpc_subscriber.clj
src/agent/http_poller.clj
src/crypto/sign.clj
src/io/grpc.cljc
src/runtime/data.clj
src/runtime/init.clj
src/sentry/logger.clj
src/tracer/honeycomb.clj
test/crypto/sign_test.clj

- Add JWT validation when setting the env `JWK_URL=`
- Releasing new versions does not update latest docker images
- Fix bug on tracer when having error on root funcs
- Fix logger bug when using sentry-logger without tags
Applying this feature will validate digital signatures of JWT tokens issued by private key's, this only works when the agent is connection through a gRPC connection and when the user is authenticating with an valid JWT token. Thus the slack tasks is disabled in this mode, executing tasks when the agent has this option enable will return the following error:
```
slack tasks are disabled, try to run it again in the webapp/cli or contact the support.
```
This feature is only useful if the an organization wants to ensure that only authenticated users from their own …

Add JWT validation

---

src/runtime/init.clj

Make values of runtime data as string to prevent breaking when sending events to gRPC API.

Fix broked agent events data

---

src/agent/agent.clj

This will allow creating custom commands with bash type and injecting the script to stdin.

Add bash to stdin input with custom commands

---

project.clj
src/agent/agent.clj
src/agent/clients.clj
src/agent/core.clj
src/agent/grpc_subscriber.clj
src/agent/http_poller.clj
src/runtime/data.clj
src/runtime/init.clj
src/tracer/honeycomb.clj

- Update gRPC clients libs
- Remove async/go calls over async/thread to avoid depleting the fixed pool of go block threads
- Make null runtime data as empty string instead of using runops:null string
- Add resilience to webhook calls over gRPC
- Allows a max of 30 tasks to run in parallel per agent

Improve the ability to run more paralell tasks with more efficience

---

project.clj
src/agent/clients.clj
src/agent/core.clj
src/logger/timbre_json.clj

- Add func to handle uncaught jvm exceptions with timbre
- Catch Throwable instead of Exception to avoid uncaught exceptions when initializing secret manager
- Bump version of `software.amazon.awssdk/secretsmanager`

Fix secret manager bug when initializing it without valid credentials

---

resources/agent.proto
src/agent/core.clj
src/agent/grpc_subscriber.clj
src/io/grpc.cljc

It will prevent from being disconnected when reaching the idle timeout of any load balancer (e.g.: aws lb, nginx)
- Add metadata when subscribing a new agent - boot, machine-id, hostname, version and revision
- Add backoff on subscribing when gRPC is connected

Add keep alive logic when processing tasks

---

src/logger/timbre.clj
src/logger/timbre_json.clj

- Fix log warn and error funcs

Make output-fn keys as PersistentArrayMap to preserve order on decoding

---

src/agent/agent.clj

- Add webhook resilience over http poller
- Removed gRPC webhook due to bug on processing unary requests
- Fix repeated slack messages when sending webhooks over gRPC

Fix webhook calls issues failing to report status of tasks

---

project.clj
resources/agent.proto
src/agent/agent.clj
src/agent/core.clj
src/agent/grpc_subscriber.clj
src/agent/http_poller.clj
src/dlp/gcp.clj
src/io/grpc.cljc
src/tracer/honeycomb.clj
test/dlp/gcp_test.clj

Add GCP DLP to agent which redact the content by findings up to 1MB, in case of errors or above that limit it will be processed by the server.
- Load dlp-fields on a per org base configuration
- Improve honeycomb instrumentation
- Add tracing metrics to webhook calls (request time, status code)
- Add dlp metrics (max findings, chunks per findings, total chunks)
- Add org, stdout, stderr and exitcode metrics

Add GCP DLP to agent

---

Dockerfile
src/agent/agent.clj

Allow executing elixir scripts in the agent. Dependencies should be passed inline. e.g.:
```elixir
Mix.install([:jason])
IO.puts(Jason.encode!(%{hello: :world}))
```

Add elixir command line

---

src/agent/agent.clj
src/dlp/gcp.clj
test/dlp/gcp_test.clj

Use DLP deidentify over manually inspect findings and redacting it.

Change dlp inspect to deidentify

---

src/agent/grpc_subscriber.clj
src/tracer/honeycomb.clj

- Add a span to identify when the agent is booting (pod restart, deploy, etc)
- Add a span to identify when the agent is receiving a task via gRPC

Enhance agent tracing

---

src/agent/agent.clj

It improves how bash parameters are interpreted when executing the k8s-exec commands

Improve k8s-exec target type

---

resources/agent.proto
src/agent/agent.clj
src/agent/core.clj
src/agent/grpc_subscriber.clj
src/io/grpc.cljc
src/runtime/init.clj

Executing tasks will perform a best-effort to upload task output to S3 via pre-signed URL's.
Added metrics to tracing (request-time, status code, chunked, protocol version)

Allow upload task output with AWS S3 pre-signed-uri

---

charts/templates/deployment.yaml
charts/templates/secrets.yaml
charts/values.yaml
setup/README.md

- Allow multiple env-vars to be specified in helm
- Updated docs
```sh
helm upgrade --install agent-dev ./charts \
--set config.token=agent-token \
--set config.tags=dev \
--set env_var[0].env=PG_CONFIG \
--set env_var[0].vars.PG_HOST=127.0.0.1 \
--set env_var[0].vars.PG_USER=root \
--set env_var[0].vars.PG_PASS=pg-root-pass \
--set env_var[0].vars.PG_DB=appdb-dev \
--set env_var[1].env=MYSQL_CONFIG \
--set env_var[1].vars.MYSQL_HOST=127.0.0.1 \
--set env_var[1].vars.MYSQL_USER=root \
--set env_var[1].vars.MYSQL_PASS=mysql-db-pass \
--set env_var[1].vars.MYSQL_DB=appdb-homolog \
--set env_var[2].env=APP_CONFIG \
--set env_var[2].vars.MYAPP_SECRET=mysuper-secret \
--set env_var[2].vars.MYAPP_KEY=appkey \
--namespace runops
```

Fix envvar to be passed correctly to a Kubernetes installation

---

src/agent/agent.clj

Report redacted to API when the agent was not able to redact due to max size.

Report redacted to API when the agent was not able to redact due to max size

---

src/agent/agent.clj

Prevents errors when passing argument list too long to the parameter:
> Cannot run program "mongo": error=7, Argument list too long

Execute mongo queries via stdin instead of passing through --eval

---

resources/agent.proto
src/agent/agent.clj
src/io/grpc.cljc

- Propagate task metadata fields: task-id, description, user-email and target which could be retrieved as environment variables in scripts types like (bash, python, node, etc).

Propagate task metadata fields to env vars

---

src/agent/agent.clj

Running a task with `k8s` type was returning the error below:
> shell command failed
No value supplied for key: [:proc-chan {:in #object[clojure.core.async.impl.channels.ManyToManyChannel 0x7ca52146 "clojure.core.async.impl.channels.ManyToManyChannel@7ca52146"], :out #object[clojure.core.async.impl.channels.ManyToManyChannel 0x12551e42 "clojure.core.async.impl.channels.ManyToManyChannel@12551e42"]}]

Pass proc-chan properly to shell/sh

---

src/agent/control_plane.clj
src/agent/types.clj

Don't allow killing tasks for `ecs-exec`, `k8s-exec` and `rails-console-ecs`

Add validation to kill task request only for certain types of task

---

src/dlp/gcp.clj

Add info type summary to identify redact issues.
The honeycomb will show the following metrics

Add info-type summary instrumentation

---

src/agent/agent.clj

Sends messages properly to stderr when a syntax error happens.

Add option to send errors to stderr for sqlcmd command

---

.gitignore
src/agent/agent.clj

Allows obtaining the user groups of a task from script types (bash, elixir, node, python, etc)

Add RUNOPS_USER_GROUPS metadata

---

Dockerfile
src/agent/agent.clj

- This change maintains [backwards compatibility](https://www.mongodb.com/docs/manual/reference/program/mongo/#std-label-compare-mongosh-mongo)
The `mongo` cli still could be used with `bash` type targets

Use mongosh instead of mongo which is deprecated

---

Dockerfile

Fix warning showing:
> Warning: Cannot create directory at `/home/runops/.cassandra`

add history dir for cqlsh cli
